// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCui4csglGcLRlzZHpeI0FW4wWL6Clg304',
    appId: '1:278569244308:web:b3196238279cd900de0681',
    messagingSenderId: '278569244308',
    projectId: 'waleti-fef1c',
    authDomain: 'waleti-fef1c.firebaseapp.com',
    storageBucket: 'waleti-fef1c.appspot.com',
    measurementId: 'G-R3JDF6EDTX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKIk3nkWZAtRdbxYqwzJzaBHZrKCm0jSw',
    appId: '1:278569244308:android:60171f939b0d1136de0681',
    messagingSenderId: '278569244308',
    projectId: 'waleti-fef1c',
    storageBucket: 'waleti-fef1c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMOMC6VCyMcq1MukGDseCOzsh2v8Fq0N4',
    appId: '1:278569244308:ios:59695448c5db2d55de0681',
    messagingSenderId: '278569244308',
    projectId: 'waleti-fef1c',
    storageBucket: 'waleti-fef1c.appspot.com',
    iosClientId: '278569244308-7v3g0n5l3tldj82u8056svmm0uj3qm7n.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterExpenseTracker',
  );
}
